"""create card face table

Revision ID: 978f2340d2d4
Revises: 9efbe8fe5b48
Create Date: 2025-12-04 15:05:56.983294

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "978f2340d2d4"
down_revision: Union[str, None] = "9efbe8fe5b48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_faces",
        sa.Column(
            "id",
            sa.String(length=36),
            nullable=False,
            comment="Primary key UUID for the card face",
        ),
        sa.Column(
            "card_id",
            sa.String(length=36),
            nullable=False,
            comment="Foreign key to the card this face belongs to",
        ),
        sa.Column("name", sa.String(length=200), nullable=False, comment="Face name"),
        sa.Column(
            "mana_cost",
            sa.String(length=20),
            nullable=True,
            comment="Mana cost of the face",
        ),
        sa.Column(
            "type_line",
            sa.String(length=200),
            nullable=True,
            comment="Type line of the face",
        ),
        sa.Column(
            "oracle_text",
            sa.Text(),
            nullable=True,
            comment="Oracle text of the face (long text)",
        ),
        sa.Column(
            "power",
            sa.String(length=10),
            nullable=True,
            comment="Power value (for creatures)",
        ),
        sa.Column(
            "toughness",
            sa.String(length=10),
            nullable=True,
            comment="Toughness value (for creatures)",
        ),
        sa.Column(
            "loyalty",
            sa.String(length=10),
            nullable=True,
            comment="Loyalty (for planeswalkers)",
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card_faces")
    # ### end Alembic commands ###
