"""create card table

Revision ID: 9efbe8fe5b48
Revises: b915dc134925
Create Date: 2025-12-04 14:53:34.410374

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "9efbe8fe5b48"
down_revision: Union[str, None] = "b915dc134925"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column(
            "id",
            sa.String(length=36),
            nullable=False,
            comment="Primary key UUID for the card",
        ),
        sa.Column(
            "external_id",
            sa.String(length=100),
            nullable=False,
            comment="Original ID from Scryfall",
        ),
        sa.Column(
            "set_id",
            sa.String(length=36),
            nullable=False,
            comment="Foreign key to the set this card belongs to",
        ),
        sa.Column("name", sa.String(length=200), nullable=False, comment="Card name"),
        sa.Column(
            "lang",
            sa.String(length=10),
            nullable=True,
            comment="Language code of the card",
        ),
        sa.Column(
            "layout",
            sa.String(length=50),
            nullable=True,
            comment="Card layout (normal, transform, split, meld, etc.)",
        ),
        sa.Column(
            "rarity",
            sa.String(length=20),
            nullable=True,
            comment="Card rarity (common, uncommon, rare, mythic)",
        ),
        sa.Column(
            "mana_cost",
            sa.String(length=20),
            nullable=True,
            comment="Mana cost of the card",
        ),
        sa.Column("cmc", sa.Integer(), nullable=True, comment="Converted mana cost"),
        sa.Column(
            "type_line",
            sa.String(length=200),
            nullable=True,
            comment="Type line of the card",
        ),
        sa.Column(
            "oracle_text",
            sa.Text(),
            nullable=True,
            comment="Oracle text of the card (long text)",
        ),
        sa.Column(
            "power",
            sa.String(length=10),
            nullable=True,
            comment="Power value (for creatures)",
        ),
        sa.Column(
            "toughness",
            sa.String(length=10),
            nullable=True,
            comment="Toughness value (for creatures)",
        ),
        sa.Column(
            "loyalty",
            sa.String(length=10),
            nullable=True,
            comment="Loyalty (for planeswalkers)",
        ),
        sa.Column(
            "collector_number",
            sa.String(length=20),
            nullable=True,
            comment="Collector number of the card",
        ),
        sa.Column(
            "is_reprint",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the card is a reprint (from Scryfall)",
        ),
        sa.Column(
            "is_reserved",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the card is on the reserved list (from Scryfall)",
        ),
        sa.Column(
            "is_full_art",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the card is full art (from Scryfall)",
        ),
        sa.Column(
            "is_textless",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the card has no text (from Scryfall)",
        ),
        sa.Column(
            "is_booster",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the card can appear in boosters (from Scryfall)",
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cards")
    # ### end Alembic commands ###
