"""add timestamp fields and descriptions

Revision ID: cd19071aac7c
Revises: 7f44db1d5872
Create Date: 2025-12-04 16:17:15.310103

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "cd19071aac7c"
down_revision: Union[str, None] = "7f44db1d5872"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_faces",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was created",
        ),
    )
    op.add_column(
        "card_faces",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was last updated",
        ),
    )
    op.add_column(
        "card_rullings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was created",
        ),
    )
    op.add_column(
        "card_rullings",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was last updated",
        ),
    )
    op.alter_column(
        "card_rullings",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment="Primary key UUID for the card rulling",
        existing_nullable=False,
    )
    op.alter_column(
        "card_rullings",
        "text",
        existing_type=sa.TEXT(),
        comment="Rulling text",
        existing_nullable=False,
    )
    op.alter_column(
        "card_rullings",
        "card_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Foreign key to the card this rulling belongs to",
        existing_nullable=False,
    )
    op.add_column(
        "cards",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was created",
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was last updated",
        ),
    )
    op.add_column(
        "set_types",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was created",
        ),
    )
    op.add_column(
        "set_types",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was last updated",
        ),
    )
    op.alter_column(
        "set_types",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment="Name of the set type",
        existing_nullable=False,
    )
    op.alter_column(
        "set_types",
        "description",
        existing_type=sa.VARCHAR(length=255),
        comment="Description of the set type",
        existing_nullable=True,
    )
    op.add_column(
        "sets",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was created",
        ),
    )
    op.add_column(
        "sets",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the set was last updated",
        ),
    )
    op.alter_column(
        "sets",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment="Primary key UUID for the set",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "external_id",
        existing_type=sa.VARCHAR(length=100),
        comment="Original ID from Scryfall",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "set_type_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Foreign key to the set type",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "code",
        existing_type=sa.VARCHAR(length=5),
        comment="Set code",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment="Set name",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "card_count",
        existing_type=sa.INTEGER(),
        comment="Number of cards in the set",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "release_date",
        existing_type=sa.VARCHAR(length=10),
        comment="Release date of the set (YYYY-MM-DD)",
        existing_nullable=True,
    )
    op.alter_column(
        "sets",
        "is_digital",
        existing_type=sa.BOOLEAN(),
        comment="Indicates if the set is digital-only",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "is_foil_only",
        existing_type=sa.BOOLEAN(),
        comment="Indicates if the set contains only foil cards",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "is_non_foil_only",
        existing_type=sa.BOOLEAN(),
        comment="Indicates if the set contains only non-foil cards",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sets",
        "is_non_foil_only",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Indicates if the set contains only non-foil cards",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "is_foil_only",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Indicates if the set contains only foil cards",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "is_digital",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Indicates if the set is digital-only",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "release_date",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="Release date of the set (YYYY-MM-DD)",
        existing_nullable=True,
    )
    op.alter_column(
        "sets",
        "card_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Number of cards in the set",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Set name",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "code",
        existing_type=sa.VARCHAR(length=5),
        comment=None,
        existing_comment="Set code",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "set_type_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Foreign key to the set type",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "external_id",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Original ID from Scryfall",
        existing_nullable=False,
    )
    op.alter_column(
        "sets",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Primary key UUID for the set",
        existing_nullable=False,
    )
    op.drop_column("sets", "updated_at")
    op.drop_column("sets", "created_at")
    op.alter_column(
        "set_types",
        "description",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Description of the set type",
        existing_nullable=True,
    )
    op.alter_column(
        "set_types",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Name of the set type",
        existing_nullable=False,
    )
    op.drop_column("set_types", "updated_at")
    op.drop_column("set_types", "created_at")
    op.drop_column("cards", "updated_at")
    op.drop_column("cards", "created_at")
    op.alter_column(
        "card_rullings",
        "card_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Foreign key to the card this rulling belongs to",
        existing_nullable=False,
    )
    op.alter_column(
        "card_rullings",
        "text",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Rulling text",
        existing_nullable=False,
    )
    op.alter_column(
        "card_rullings",
        "id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Primary key UUID for the card rulling",
        existing_nullable=False,
    )
    op.drop_column("card_rullings", "updated_at")
    op.drop_column("card_rullings", "created_at")
    op.drop_column("card_faces", "updated_at")
    op.drop_column("card_faces", "created_at")
    # ### end Alembic commands ###
