"""create set table

Revision ID: b915dc134925
Revises: 261d075a7d96
Create Date: 2025-12-04 14:29:06.646056

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "b915dc134925"
down_revision: Union[str, None] = "261d075a7d96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("set_type_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("card_count", sa.Integer(), nullable=False),
        sa.Column("release_date", sa.String(length=10), nullable=True),
        sa.Column("is_digital", sa.Boolean(), nullable=False),
        sa.Column("is_foil_only", sa.Boolean(), nullable=False),
        sa.Column("is_nonfoil_only", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["set_type_id"],
            ["set_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("external_id"),
        sa.UniqueConstraint("set_type_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sets")
    # ### end Alembic commands ###
