"""add colors field in card face table

Revision ID: c5c83d10c36e
Revises: 78c9b07d792f
Create Date: 2025-12-15 01:24:46.051739

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c5c83d10c36e'
down_revision: Union[str, None] = '78c9b07d792f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_faces', sa.Column('colors', postgresql.ARRAY(sa.Enum('W', 'U', 'B', 'R', 'G', name='color_enum', native_enum=False)), nullable=True))
    op.add_column('card_faces', sa.Column('color_identity', postgresql.ARRAY(sa.Enum('W', 'U', 'B', 'R', 'G', name='color_enum', native_enum=False)), nullable=True))
    op.drop_constraint(op.f('card_faces_card_id_fkey'), 'card_faces', type_='foreignkey')
    op.create_foreign_key(None, 'card_faces', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card_faces', type_='foreignkey')
    op.create_foreign_key(op.f('card_faces_card_id_fkey'), 'card_faces', 'cards', ['card_id'], ['id'])
    op.drop_column('card_faces', 'color_identity')
    op.drop_column('card_faces', 'colors')
    # ### end Alembic commands ###
