"""change column name

Revision ID: 462f0b9ec2b8
Revises: d27c3f3e297a
Create Date: 2025-12-07 13:47:39.659696

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "462f0b9ec2b8"
down_revision: Union[str, None] = "d27c3f3e297a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sets",
        sa.Column(
            "is_non_foil_only",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the set contains only non-foil cards",
        ),
    )
    op.drop_column("sets", "is_non_foil_only")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sets",
        sa.Column(
            "is_non_foil_only",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Indicates if the set contains only non-foil cards",
        ),
    )
    op.drop_column("sets", "is_non_foil_only")
    # ### end Alembic commands ###
