"""update mana cost fields length

Revision ID: 78c9b07d792f
Revises: 58107c806f4d
Create Date: 2025-12-12 12:48:31.638058

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '78c9b07d792f'
down_revision: Union[str, None] = '58107c806f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_faces', 'mana_cost',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_comment='Mana cost of the face',
               existing_nullable=True)
    op.alter_column('cards', 'external_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_comment='Original ID from Scryfall',
               existing_nullable=False)
    op.alter_column('cards', 'mana_cost',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_comment='Mana cost of the card',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'mana_cost',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_comment='Mana cost of the card',
               existing_nullable=True)
    op.alter_column('cards', 'external_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_comment='Original ID from Scryfall',
               existing_nullable=False)
    op.alter_column('card_faces', 'mana_cost',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_comment='Mana cost of the face',
               existing_nullable=True)
    # ### end Alembic commands ###
