"""update card rulling table

Revision ID: 9a6d4191b876
Revises: 9813a1e314c8
Create Date: 2025-12-09 08:08:46.793468

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "9a6d4191b876"
down_revision: Union[str, None] = "9813a1e314c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_rullings",
        sa.Column(
            "oracle_id",
            sa.String(length=36),
            nullable=False,
            comment="Oracle ID associated with the card rulling",
        ),
    )
    op.add_column(
        "card_rullings",
        sa.Column("comment", sa.Text(), nullable=False, comment="Rulling text"),
    )
    op.add_column(
        "card_rullings",
        sa.Column(
            "source",
            sa.String(length=255),
            nullable=False,
            comment="Source of the rulling",
        ),
    )
    op.drop_column("card_rullings", "text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_rullings",
        sa.Column(
            "text",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="Rulling text",
        ),
    )
    op.drop_column("card_rullings", "source")
    op.drop_column("card_rullings", "comment")
    op.drop_column("card_rullings", "oracle_id")
    # ### end Alembic commands ###
