"""add icon uri column

Revision ID: 9813a1e314c8
Revises: 462f0b9ec2b8
Create Date: 2025-12-07 20:35:44.726986

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "9813a1e314c8"
down_revision: Union[str, None] = "462f0b9ec2b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sets",
        sa.Column(
            "icon_uri",
            sa.String(length=255),
            nullable=True,
            comment="URI for the set icon image",
        ),
    )
    op.drop_column("sets", "is_nonfoil_only")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sets",
        sa.Column(
            "is_nonfoil_only",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Indicates if the set contains only non-foil cards",
        ),
    )
    op.drop_column("sets", "icon_uri")
    # ### end Alembic commands ###
