"""make set_type_id nullable

Revision ID: d27c3f3e297a
Revises: cd19071aac7c
Create Date: 2025-12-07 13:05:24.920058

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

revision: str = "d27c3f3e297a"
down_revision: Union[str, None] = "cd19071aac7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("sets_set_type_id_key"), "sets", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("sets_set_type_id_key"),
        "sets",
        ["set_type_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
