"""update card table

Revision ID: d990023dd35f
Revises: 9a6d4191b876
Create Date: 2025-12-09 11:21:46.262989

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d990023dd35f"
down_revision: Union[str, None] = "9a6d4191b876"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards",
        sa.Column(
            "oracle_id",
            sa.String(length=36),
            nullable=False,
            comment="Scryfall oracle_id",
        ),
    )
    op.add_column("cards", sa.Column("released_at", sa.Date(), nullable=False))
    op.add_column(
        "cards",
        sa.Column(
            "security_stamp",
            sa.Enum(
                "oval",
                "triangle",
                "acorn",
                "circle",
                "arena",
                "heart",
                name="security_stamp_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "border_color",
            sa.Enum(
                "black",
                "white",
                "borderless",
                "yellow",
                "silver",
                "gold",
                name="border_color_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "colors",
            postgresql.ARRAY(
                sa.Enum("W", "U", "B", "R", "G", name="color_enum", native_enum=False)
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "color_identity",
            postgresql.ARRAY(
                sa.Enum("W", "U", "B", "R", "G", name="color_enum", native_enum=False)
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "cards", sa.Column("keywords", postgresql.ARRAY(sa.VARCHAR()), nullable=True)
    )
    op.add_column(
        "cards",
        sa.Column(
            "legalities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Legalities info for every game format, as provided by Scryfall",
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "finishes",
            postgresql.ARRAY(
                sa.Enum(
                    "foil", "non_foil", "etched", name="finish_enum", native_enum=False
                )
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "image_uris",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Image URIs from Scryfall",
        ),
    )
    op.add_column(
        "cards",
        sa.Column(
            "is_found_on_booster",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the card can appear in boosters (from Scryfall)",
        ),
    )
    op.add_column("cards", sa.Column("is_foil", sa.Boolean(), nullable=False))
    op.add_column("cards", sa.Column("is_non_foil", sa.Boolean(), nullable=False))
    op.add_column("cards", sa.Column("is_game_changer", sa.Boolean(), nullable=False))
    op.add_column("cards", sa.Column("is_oversized", sa.Boolean(), nullable=False))
    op.add_column("cards", sa.Column("is_promo", sa.Boolean(), nullable=False))
    op.add_column("cards", sa.Column("is_variation", sa.Boolean(), nullable=False))
    op.alter_column(
        "cards",
        "rarity",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "common",
            "uncommon",
            "rare",
            "mythic",
            "special",
            "bonus",
            name="rarity_enum",
            native_enum=False,
        ),
        existing_comment="Card rarity (common, uncommon, rare, mythic)",
        existing_nullable=True,
    )
    op.drop_column("cards", "is_booster")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards",
        sa.Column(
            "is_booster",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Indicates if the card can appear in boosters (from Scryfall)",
        ),
    )
    op.alter_column(
        "cards",
        "rarity",
        existing_type=sa.Enum(
            "common",
            "uncommon",
            "rare",
            "mythic",
            "special",
            "bonus",
            name="rarity_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_comment="Card rarity (common, uncommon, rare, mythic)",
        existing_nullable=True,
    )
    op.drop_column("cards", "is_variation")
    op.drop_column("cards", "is_promo")
    op.drop_column("cards", "is_oversized")
    op.drop_column("cards", "is_game_changer")
    op.drop_column("cards", "is_non_foil")
    op.drop_column("cards", "is_foil")
    op.drop_column("cards", "is_found_on_booster")
    op.drop_column("cards", "image_uris")
    op.drop_column("cards", "finishes")
    op.drop_column("cards", "legalities")
    op.drop_column("cards", "keywords")
    op.drop_column("cards", "color_identity")
    op.drop_column("cards", "colors")
    op.drop_column("cards", "border_color")
    op.drop_column("cards", "security_stamp")
    op.drop_column("cards", "released_at")
    op.drop_column("cards", "oracle_id")
    # ### end Alembic commands ###
