"""update card faces table

Revision ID: e89998c53cd6
Revises: 2af9aaea640e
Create Date: 2025-12-12 12:07:00.375687

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e89998c53cd6"
down_revision: Union[str, None] = "2af9aaea640e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_faces",
        sa.Column(
            "oracle_id",
            sa.String(length=36),
            nullable=True,
            comment="Scryfall oracle_id",
        ),
    )
    op.add_column(
        "card_faces",
        sa.Column(
            "image_uris",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Image URIs from Scryfall",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card_faces", "image_uris")
    op.drop_column("card_faces", "oracle_id")
    # ### end Alembic commands ###
