"""add cmc field

Revision ID: 58107c806f4d
Revises: e89998c53cd6
Create Date: 2025-12-12 12:20:26.745579

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "58107c806f4d"
down_revision: Union[str, None] = "e89998c53cd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_faces",
        sa.Column("cmc", sa.Integer(), nullable=True, comment="Converted mana cost"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card_faces", "cmc")
    # ### end Alembic commands ###
