"""update cards table

Revision ID: 2af9aaea640e
Revises: 1319ff257ec8
Create Date: 2025-12-12 12:04:44.751432

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2af9aaea640e"
down_revision: Union[str, None] = "1319ff257ec8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cards",
        "oracle_id",
        existing_type=sa.VARCHAR(length=36),
        nullable=True,
        existing_comment="Scryfall oracle_id",
    )
    op.alter_column(
        "cards",
        "image_uris",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_comment="Image URIs from Scryfall",
    )
    op.drop_column("cards", "is_foil")
    op.drop_column("cards", "is_nonfoil")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards",
        sa.Column("is_nonfoil", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "cards", sa.Column("is_foil", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.alter_column(
        "cards",
        "image_uris",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_comment="Image URIs from Scryfall",
    )
    op.alter_column(
        "cards",
        "oracle_id",
        existing_type=sa.VARCHAR(length=36),
        nullable=False,
        existing_comment="Scryfall oracle_id",
    )
    # ### end Alembic commands ###
