"""update non_foil to nonfoil

Revision ID: 1319ff257ec8
Revises: d990023dd35f
Create Date: 2025-12-10 11:28:32.471625

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1319ff257ec8"
down_revision: Union[str, None] = "d990023dd35f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("is_nonfoil", sa.Boolean(), nullable=False))
    op.alter_column(
        "cards",
        "finishes",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=8)),
        type_=postgresql.ARRAY(
            sa.Enum("foil", "nonfoil", "etched", name="finish_enum", native_enum=False)
        ),
        existing_nullable=False,
    )
    op.drop_column("cards", "is_non_foil")
    op.add_column(
        "sets",
        sa.Column(
            "is_nonfoil_only",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the set contains only non-foil cards",
        ),
    )
    op.drop_column("sets", "is_non_foil_only")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sets",
        sa.Column(
            "is_non_foil_only",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Indicates if the set contains only non-foil cards",
        ),
    )
    op.drop_column("sets", "is_nonfoil_only")
    op.add_column(
        "cards",
        sa.Column("is_non_foil", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "cards",
        "finishes",
        existing_type=postgresql.ARRAY(
            sa.Enum("foil", "nonfoil", "etched", name="finish_enum", native_enum=False)
        ),
        type_=postgresql.ARRAY(sa.VARCHAR(length=8)),
        existing_nullable=False,
    )
    op.drop_column("cards", "is_nonfoil")
    # ### end Alembic commands ###
