"""remove oracle_id field from card rulling table

Revision ID: bf703010d8ae
Revises: c5c83d10c36e
Create Date: 2025-12-18 11:23:42.161301

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "bf703010d8ae"
down_revision: Union[str, None] = "c5c83d10c36e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card_rullings", "oracle_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_rullings",
        sa.Column(
            "oracle_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
            comment="Oracle ID associated with the card rulling",
        ),
    )
    # ### end Alembic commands ###
