"""add published_at field in card ruling table

Revision ID: e019a3caa99f
Revises: bf703010d8ae
Create Date: 2025-12-18 12:24:07.292147

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e019a3caa99f'
down_revision: Union[str, None] = 'bf703010d8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_rullings', sa.Column('published_at', sa.String(length=25), nullable=False, comment='Published date of the rulling'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_rullings', 'published_at')
    # ### end Alembic commands ###
